version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: magasinpswd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  sales-service:
    build: ./sales-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  reporting-service:
    build: ./reporting-service
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  customer-service:
    build: ./customer-service
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  cart-service:
    build: ./cart-service
    ports:
      - "8086:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  order-service:
    build: ./order-service
    ports:
      - "8087:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

volumes:
  postgres_data: 