version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lab5_postgres
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: magasinpswd
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/local_backup.sql:/docker-entrypoint-initdb.d/local_backup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magasin_user -d magasin"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  db_data: 